language: go

go: 
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1  

notifications:
  email: true

sudo: required

services: 
  - docker

install:
  - echo "this is install section"
  - go get github.com/gorilla/websocket
  - go get github.com/stretchr/testify/assert
  - make image-dev
 
script:
  - echo "this is script section"
  - go test -v ./...
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make push-dev  